config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :flights
  resources :bookings do
    collection do
      get 'flight_book'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  after_create :set_pnr_number 
  after_commit :create_total 
  belongs_to :flight

  def set_pnr_number
    pnr_number = self.seat_class + '_'  +SecureRandom.urlsafe_base64(8)
    self.update_column(:pnr_number, pnr_number) 
  end

  def create_total
    seat_per_price = self.flight.seatings.find_by(name: self.seat_class).seat_price
    total = self.seat * self.flight.seatings.find_by(name: self.seat_class).seat_price
    self.update_column(:total_amount, total) 
  end
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :bookings
  has_many :seatings
  accepts_nested_attributes_for :seatings
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/seating.rb
class Seating < ApplicationRecord
  belongs_to :flight
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   has_and_belongs_to_many :flights

   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	before_action :get_flight, only: [:new,:create]
	before_action :get_booking, only: [:edit , :update]

	def flight_book
		@flight_seatings = Flight.find(params[:flight_number]).seatings
		
	end

	def new
		@booking = @flight.bookings.new
		@classes = @flight.seatings
	end

	def create
		@booking = @flight.bookings.new(booking_params)
		seat_class = Seating.find(params[:booking]['seat_class']).name
		@booking.seat_class = seat_class
		@remaining_seats = (@flight.seats - params[:booking]['seat'].to_i)
		if @booking.save
			@flight.update(seats: @remaining_seats)
			redirect_to booking_path(@booking.id)
    end
  end

  def edit
  	@classes = @booking.flight.seatings
  end

  def update
  	seat_class = Seating.find(params[:booking]['seat_class']).name
  	@booking.update(name: params[:booking]['name'], age: params[:booking]['age'], seat: params[:booking]['seat'],seat_class: seat_class)
  	redirect_to booking_path(@booking.id)
  end

  def show
  	@booking = Booking.find(params[:id])	
  end

  private

	def booking_params
		params.require(:booking).permit(:name,:age,:seat)
	end

	def get_booking
		@booking = Booking.find(params[:id])
		
	end

	def get_flight
		if params[:flight].present?
			@flight = Flight.find(params[:flight])
		else
			@flight = Flight.find(params[:booking]['flight'])
		end
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
  	@flights = Flight.all
  end

	def new
		@flight = Flight.new
		# @seatings = @flight.seatings.build
	end

	def create
		@flight = Flight.create(flight_params)
		redirect_to flight_path(id: @flight.id)
  end

  def book_flight
  	
  end
 
  def show
  	@flight = Flight.find(params[:id])
  end


	private
	def flight_params
		params.require(:flight).permit(:name,:origin,:destination,:seats,:pnr_number, seatings_attributes: [ :name, :seats ,:number_of_rows,:row_seats,:seat_price,:_destroy])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookings/_form.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header"><h2>Book a Flight</h2></div>
      <div class="card-body">
				<%=form_for @booking do |f|%>
				<div class="field form-group">
          <div class="row">
           	<div class="col-sm-4">
           		<%=f.label 'name' %>:
           	</div>
           	<div class="col-sm-8">
							<%=f.text_field :name , class: "form-control" %>
						</div>
					</div>
				</div>
				<%= f.hidden_field 'flight', :value => params[:flight] %>
    		<div class="field form-group">
          <div class="row">
           	<div class="col-sm-4">
           		<%=f.label 'age' %>:
           	</div>
           	<div class="col-sm-8">
							<%=f.number_field :age , class: "form-control" %>
						</div>
					</div>
				</div>
				<div class="field form-group">
          <div class="row">
           	<div class="col-sm-4">
           		<%=f.label 'seat'%>
           	</div>
           	<div class="col-sm-8">
							<%=f.number_field :seat, class: "form-control"%>
						</div>
					</div>
				</div>

				<div class="field form-group">
          <div class="row">
           	<div class="col-sm-4">
							<%=f.label 'seat_class'%>
						</div>
					  <div class="col-sm-8">
							<%= f.collection_select :seat_class, @classes, :id, :name %>

						</div>
					</div>
				</div>
				<div class="field form-group">
          <div class="row justify-content-md-center">
          	<%= f.submit%>
          </div>
        </div>

		<%end%>

app/views/bookings/edit.html.erb
<%= render "form" %>

app/views/bookings/flight_book.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
<% @flight_seatings.each do | flight_seat | %>  
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= flight_seat.name %></h5>
          <% @total_seats = Array.new(flight_seat.seats.to_i, 1) %>
          <% @total_seats.each do | seat |  %>
            <%= link_to new_booking_path(flight: params[:flight_number]) do %>
              <i class='fas fa-chair'></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/new.html.erb
<%= render "form" %>

app/views/bookings/show.html.erb
Name:  <%= @booking.name %></br>
Age:  <%= @booking.age %></br>
Seat:  <%= @booking.seat %></br>
Class: <%= @booking.seat_class %></br>
PNR_ Number <%= @booking.pnr_number %></br>
Total_amount <%= @booking.total_amount %></br>
<%= link_to 'Upgrade' ,edit_booking_path(@booking) %>

app/views/flights/_seating_fields.html.erb
<h3> Seat Configuration</h3>
<div class="field form-group">
  <div class="row">
    <div class="col-sm-4">  
      <%= f.label "seat_class" %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name , class: "form-control"%>
    </div>
  </div>
</div>
<div class="field form-group">
  <div class="row">
    <div class="col-sm-4">  
      <%= f.label "seat_price" %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :seat_price , class: "form-control"%>
    </div>
  </div>
</div>
<div class="field form-group">
  <div class="row">
    <div class="col-sm-4">  
      <%= f.label "seats" %>
    </div>
    <div class="col-sm-8">
      <%= f.number_field :seats, class: "form-control" %>
    </div>
  </div>
</div>
<div class="field form-group">
  <div class="row">
    <div class="col-sm-4">  
      <%= f.label "Number of rows" %>
    </div>
    <div class="col-sm-8">
      <%= f.number_field :number_of_rows, class: "form-control" %>
    </div>
  </div>
</div>
<div class="field form-group">
  <div class="row">
    <div class="col-sm-4">  
      <%= f.label "Row seats" %>
    </div>
    <div class="col-sm-8">
      <%= f.number_field :row_seats, class: "form-control" %>
    </div>
  </div>
</div>
    <%#= link_to_remove_association "Delete", f %>

app/views/flights/book_flight.html.erb
<p> hiii</p>

app/views/flights/index.html.erb
<div class="row">
  <% @flights.each do | flight | %>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= flight.name %></h5>
          <h6 class="card-title"><b>From: </b> <%= flight.origin %></h6>
          <h6 class="card-title"><b>To:</b>  <%= flight.destination %></h6>
          <h6 class="card-title"><b>Total Seats:</b>  <%= flight.seats %></h6>
          <a href="<%= flight_book_bookings_path(total_seats: flight.seats, flight_number: flight.id) %>" class="btn btn-primary">Book Flight</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flights/new.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
  <%=link_to 'Back',root_path%>

  <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
</nav>

<div class="row justify-content-center">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header"><h2>Create Flight</h2></div>
      <div class="card-body">
        <%=form_for @flight do |f|%>
          <div class="field form-group">
            <div class="row">
              <div class="col-sm-4">
                <%=f.label 'name' %>:
              </div>
              <div class="col-sm-8">
                <%=f.text_field :name , class: "form-control"  %>
              </div>
            </div>
          </div>
          <div class="field form-group">
            <div class="row">
              <div class="col-sm-4">
                <%=f.label 'Origin' %>:
              </div>
              <div class="col-sm-8">
                <%=f.text_field :origin , class: "form-control" %><br>
              </div>
            </div>
          </div>
          <div class="field form-group">
            <div class="row">
              <div class="col-sm-4">
                <%=f.label 'Destination'%>:
              </div>
              <div class="col-sm-8">
                <%=f.text_field :destination , class: "form-control"%>
              </div>
            </div>
          </div>
          <div class="field form-group">
            <div class="row">
              <div class="col-sm-4">      
                <%=f.label 'Seats'%>:
              </div>
              <div class="col-sm-8">
                <%=f.text_field :seats , class: "form-control"%>
              </div>
            </div>
          </div>
          <div class="field form-group">
            <div class="row">
              <div class="col-sm-4">    
                <%=f.label 'Pnr_Number'%>:
              </div>
              <div class="col-sm-8">
                <%=f.text_field :pnr_number , class: "form-control"%>
              </div>
            </div>
          </div>
          <div>
            <%= link_to_add_association "Add seating_configuration", f, :seatings %> 
          </div>
            
          <div class="field form-group">
            <div class="row justify-content-md-center">
                <%= f.submit %>
            </div>
          </div>
      <%end%>
    </div>
  </div>
</div>
  

app/views/flights/show.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
  <%=link_to 'Back',root_path%>

  <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
</nav>

<h1>Booked Flights</h1>
<table border=1>
<tr>
	<th>Origin</th>
	<th>Destination</th>
	<th>Seats</th>
	<th>PNR_Number</th>
</tr>

  <tr>
	  <td><%=@flight.origin%></td>
	  <td><%=@flight.destination%></td>
	  <td><%=@flight.seats%></td>
	  <td><%=@flight.pnr_number%></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>


      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <div class="card" style="width: 10rem;margin-left: 500px;">
        <div class="card-body">
          <a href="/flights/new" class="btn btn-secondary">Create flight</a>
        </div>
      </div>
      <nav class="navbar navbar-light bg-light" style="margin-top: -130px;">
        
        <%= link_to "Logout", destroy_user_session_path, method: :delete, style: 'margin-left: 1500px;'  %>
      </nav>
    <% else %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% end %>
<% else %>
  <div class="card" style="width: 18rem;margin-left: 500px;">
    <div class="card-body">
      <a href="<%= flights_path %>" class="btn btn-secondary">Book a flight</a>
      <a href="<%= new_user_session_path %>" class="btn btn-primary" style="margin-left: 12px;">Admin login</a>
    </div>
  </div>
<% end %>